######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 23 14:59:41 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h thread.h ui.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp thread.cpp
